# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0002_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Nickname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score', models.IntegerField(blank=True, max_length=1000000, null=True, verbose_name='Score')),
            ],
        ),
    ]
