# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nickname',
            new_name='name',
        ),
    ]
